# Namespaces - It provide a mechanism for isolating groups of resources within a single cluster
# Names of resources need to be unique within a namespace, but not across namespaces.

apiVersion: v1
kind: Namespace
metadata:
  name: expense   # name of the namespace
  labels:
    project: expense
    environment: dev

# To view the namespaces  -  kubectl get namespace

#What Are Namespaces?
#Kubernetes namespaces provide a way to logically divide resources and workloads into separate environments within the same cluster. They allow teams to operate in isolation without interfering with each other’s resources. It’s crucial for large-scale environments where multiple teams or applications share the same infrastructure.

#Namespaces help with:

#Resource Management: Allocate and limit resources for each namespace to prevent resource contention.
#Access Control: Apply RBAC (Role-Based Access Control) policies to restrict access at a namespace level.
#Environment Isolation: Different teams or applications can run their workloads in isolated namespaces, which reduces conflicts.
#Simplified Management: Efficiently manage and monitor workloads with namespaces that represent different environments (e.g., dev, test, prod).